### ISSUE TITLE
New Feature Request - Add view angle offset

### ISSUE THREAD

**Issue by ClaraYW** [hellojeffhall/simple-stl-viewer#1]
Hello Jeff!
Thank you for sharing this 3D model display library. This is Amazing! :)
Currently, the STL auto-rotate on the front view. I wonder if you can add a feature that allows user to decide which angle it will auto-rotate from. If this is too time-consuming. The MVP needs for this feature is to make it auto-rotate at 45 degrees between the x-axis and z-axis. Thank you!

**Comment by hellojeffhall** [comment]
Thank you for the suggestion! This is now implemented in version 1.0.1. 

To use this feature, please update your script tag to use this URL:

`<script src="https://cdn.jsdelivr.net/gh/hellojeffhall/simple-stl-viewer@main/dist/simple-stl-viewer.1.0.1.min.js"></script>
`

And in your placeholder `<div>`, please add a `data-angle-offset-x` property, e.g., 

`<div data-color='#5A7A7C' data-stl-url='assets/dizang.stl' data-angle-offset-x='-45'></div>`
